/**
 * Paging, and the rule that `select` is mandatory.
 *
 * `retrieveMultipleRecordsAsync` returns one page plus a `skipToken`. The canvas app had no
 * equivalent: `ClearCollect` simply stopped at
 * `DefaultConnectedDataSourceMaxGetRowsCount: 2000` and gave no indication it had truncated.
 * `fetchAll` follows the token, so a project with more cost rows than the old cap does not
 * quietly lose them.
 */
import type { IOperationOptions, IOperationResult } from "@microsoft/power-apps/data";
import { getClient } from "@microsoft/power-apps/data";
// Generated by `pac code add-data-source`; the same import the generated services use.
import { dataSourcesInfo } from "../../.power/schemas/appschemas/dataSourcesInfo";
import { unwrap } from "@/platform/errors";
import { trace } from "@/platform/telemetry";

/** One page of a table. */
type PageFn<T> = (options: IOperationOptions) => Promise<IOperationResult<T[]>>;

export interface FetchAllOptions extends Omit<IOperationOptions, "filter"> {
  /**
   * `$select` is required, not optional. Dataverse returns EVERY column without it — on
   * `vsb_projects` that is 112 columns per row — and the formatted-value annotations on top.
   */
  select: string[];
  /**
   * Optional, and `undefined` means NO `$filter` at all.
   *
   * The builders in `./odata` return `undefined` rather than `""` for exactly this reason:
   * an empty `$filter=` is a 400, so the key is stripped below instead of forwarded blank.
   */
  filter?: string | undefined;
  /** Safety valve. Exceeding it is a bug in the caller's filter, so it traces loudly. */
  maxPages?: number;
}

/** Drops keys whose value is undefined, so `{filter: undefined}` never becomes `$filter=`. */
function compact(options: Record<string, unknown>): IOperationOptions {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(options)) if (v !== undefined) out[k] = v;
  return out as IOperationOptions;
}

const DEFAULT_MAX_PAGES = 50;
const DEFAULT_PAGE_SIZE = 500;

export async function fetchAll<T>(
  operation: string,
  page: PageFn<T>,
  options: FetchAllOptions,
): Promise<T[]> {
  const { maxPages = DEFAULT_MAX_PAGES, ...query } = options;
  const rows: T[] = [];
  let skipToken: string | undefined;
  let pages = 0;

  do {
    const result = await page(compact({
      maxPageSize: DEFAULT_PAGE_SIZE,
      ...query,
      ...(skipToken ? { skipToken } : {}),
    }));
    rows.push(...unwrap(result, `${operation} (page ${pages + 1})`));
    skipToken = result.skipToken;
    pages += 1;
    if (pages >= maxPages && skipToken) {
      // Truncating silently is exactly the canvas behaviour this function exists to avoid,
      // so say so rather than returning a plausible-looking short list.
      trace(
        "error",
        `${operation} stopped after ${pages} pages with more rows available — the filter is too broad`,
        { rows: rows.length },
      );
      break;
    }
  } while (skipToken);

  return rows;
}

/** A single page, for the cases where one page is genuinely all that is wanted. */
export async function fetchPage<T>(
  operation: string,
  page: PageFn<T>,
  options: FetchAllOptions,
): Promise<T[]> {
  const { maxPages: _ignored, ...query } = options;
  return unwrap(
    await page(compact({ maxPageSize: DEFAULT_PAGE_SIZE, ...query })),
    operation,
  );
}

/* ══════════════════════════════════════════════════════ counted paging ══ */

/**
 * A page of rows plus the server-side total, paged with a SKIP TOKEN.
 *
 * **Dataverse does not support `$skip`.** It answers
 * `{"code":"0x80060888","message":"Skip Clause is not supported in CRM"}`. Paging is
 * forward-only through `@odata.nextLink`, which the SDK surfaces as `skipToken` on both the
 * request and the result. That is why this walks rather than jumps, and it is also why the
 * canvas pager only ever had First / Previous / Next and no page-number box.
 *
 * Tokens are cached per query signature so Previous is free and a re-render does not re-walk.
 * A shared link that names page 3 walks pages 1 and 2 to get there — two extra round trips,
 * once, which is the honest cost of a forward-only cursor.
 *
 * Why not the generated service: `IGetAllOptions` in `src/generated/models/CommonModels.ts`
 * declares no `count`, though the SDK's `IOperationOptions` does and the runtime honours it.
 * That file is pac output and must not be hand-edited.
 *
 * `@odata.count` is capped at 5000 by the platform, so a filtered set larger than that
 * reports exactly 5000. At 1,129 projects that is far off, but it is a real ceiling.
 */
export interface CountedPage<T> {
  rows: T[];
  /** `@odata.count` for the whole filtered set. Capped at 5000 by the platform. */
  totalRows: number;
  /** 1-based, and clamped to what actually exists. */
  page: number;
  /** True when the server returned a token for a further page. */
  hasNext: boolean;
}

/** Token caches, keyed by query signature. `tokens[0]` is always undefined — page 1. */
const tokenCache = new Map<string, (string | undefined)[]>();

/** Discards the walk when the filter or sort changes; a stale token returns the wrong rows. */
export function resetPageTokens(signature?: string): void {
  if (signature === undefined) tokenCache.clear();
  else tokenCache.delete(signature);
}

export interface CountedPageRequest extends FetchAllOptions {
  /** Rows per page. */
  top: number;
  /** 1-based. */
  page: number;
  /**
   * Identifies the query the tokens belong to — the filter and the sort. Two different
   * filters must never share a token.
   */
  signature: string;
}

export async function countedPage<T>(
  operation: string,
  tableName: string,
  request: CountedPageRequest,
): Promise<CountedPage<T>> {
  const { maxPages: _ignored, page, signature, ...query } = request;
  const client = getClient(dataSourcesInfo);
  const wanted = Math.max(1, Math.floor(page) || 1);

  const tokens = tokenCache.get(signature) ?? [undefined];
  tokenCache.set(signature, tokens);

  const fetchAt = async (index: number) => {
    const result = await client.retrieveMultipleRecordsAsync<T>(
      tableName,
      compact({ ...query, count: true, skipToken: tokens[index] }),
    );
    const rows = unwrap(result, `${operation} (page ${index + 1})`);
    // Remember the token that reaches the NEXT page, so Previous never re-walks.
    if (result.skipToken) tokens[index + 1] = result.skipToken;
    return { rows, totalRows: result.count ?? rows.length, next: result.skipToken };
  };

  let index = 0;
  let current = await fetchAt(0);

  // Walk forward to the requested page, stopping early if the data runs out.
  while (index + 1 < wanted && current.next) {
    index += 1;
    current = await fetchAt(index);
  }

  return {
    rows: current.rows,
    totalRows: current.totalRows,
    page: index + 1,
    hasNext: Boolean(current.next),
  };
}
